#ifndef WPWIKI_VERSION_H
#define WPWIKI_VERSION_H

// This file was generated by ecm_setup_version(): DO NOT EDIT!

#define WPWIKI_VERSION_STRING "1.0.0"
#define WPWIKI_VERSION_MAJOR 1
#define WPWIKI_VERSION_MINOR 0
#define WPWIKI_VERSION_PATCH 0
#define WPWIKI_VERSION ((1 << 16)|(0 << 8)|(0))

#endif // WPWIKI_VERSION_H
